# Generated by Django 5.2.4 on 2025-07-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('date', models.CharField(max_length=300)),
                ('clas', models.CharField(max_length=300)),
                ('dept', models.CharField(max_length=300)),
                ('roll', models.CharField(max_length=300)),
                ('tel', models.CharField(max_length=300)),
            ],
        ),
    ]
