# Generated by Django 5.2.4 on 2025-07-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='clas',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='article',
            name='dept',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='article',
            name='roll',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='article',
            name='tel',
            field=models.CharField(max_length=20),
        ),
    ]
