# Generated by Django 5.2.4 on 2025-07-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_article_clas_alter_article_dept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.CharField(max_length=25),
        ),
    ]
