# Generated by Django 5.2.4 on 2025-07-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_article_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='article',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tel',
        ),
    ]
